version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: goldcert
      POSTGRES_USER: goldcert
      POSTGRES_PASSWORD: goldcert
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      POSTGRES_URL: postgresql+psycopg2://goldcert:goldcert@db:5432/goldcert
      JWT_SECRET: change-me
    depends_on:
      - db
    ports:
      - "5000:5000"
volumes:
  db_data:
