services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: goldcert
      POSTGRES_USER: goldcert
      POSTGRES_PASSWORD: goldcert
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goldcert -d goldcert"]
      interval: 5s
      timeout: 5s
      retries: 15

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

volumes:
  db_data:
